# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcappFrame(wx.Frame):
#!XRCED:begin-block:xrcappFrame.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcappFrame.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "appFrame")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers

        self.Bind(wx.EVT_MENU, self.OnMenu_new, id=xrc.XRCID('new'))
        self.Bind(wx.EVT_MENU, self.OnMenu_open, id=xrc.XRCID('open'))
        self.Bind(wx.EVT_MENU, self.OnMenu_save, id=xrc.XRCID('save'))
        self.Bind(wx.EVT_MENU, self.OnMenu_saveAs, id=xrc.XRCID('saveAs'))
        self.Bind(wx.EVT_MENU, self.OnMenu_exit, id=xrc.XRCID('exit'))
        self.Bind(wx.EVT_TOOL, self.OnTool_tbNew, id=xrc.XRCID('tbNew'))
        self.Bind(wx.EVT_TOOL, self.OnTool_tbSave, id=xrc.XRCID('tbSave'))
        self.Bind(wx.EVT_TOOL, self.OnTool_tbSaveAs, id=xrc.XRCID('tbSaveAs'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_fooButton, id=xrc.XRCID('fooButton'))

#!XRCED:begin-block:xrcappFrame.OnMenu_new
    def OnMenu_new(self, evt):
        # Replace with event handler code
        print "OnMenu_new()"
#!XRCED:end-block:xrcappFrame.OnMenu_new        

#!XRCED:begin-block:xrcappFrame.OnMenu_open
    def OnMenu_open(self, evt):
        # Replace with event handler code
        print "OnMenu_open()"
#!XRCED:end-block:xrcappFrame.OnMenu_open        

#!XRCED:begin-block:xrcappFrame.OnMenu_save
    def OnMenu_save(self, evt):
        # Replace with event handler code
        print "OnMenu_save()"
#!XRCED:end-block:xrcappFrame.OnMenu_save        

#!XRCED:begin-block:xrcappFrame.OnMenu_saveAs
    def OnMenu_saveAs(self, evt):
        # Replace with event handler code
        print "OnMenu_saveAs()"
#!XRCED:end-block:xrcappFrame.OnMenu_saveAs        

#!XRCED:begin-block:xrcappFrame.OnMenu_exit
    def OnMenu_exit(self, evt):
        # Replace with event handler code
        print "OnMenu_exit()"
#!XRCED:end-block:xrcappFrame.OnMenu_exit        

#!XRCED:begin-block:xrcappFrame.OnTool_tbNew
    def OnTool_tbNew(self, evt):
        # Replace with event handler code
        print "OnTool_tbNew()"
#!XRCED:end-block:xrcappFrame.OnTool_tbNew        

#!XRCED:begin-block:xrcappFrame.OnTool_tbSave
    def OnTool_tbSave(self, evt):
        # Replace with event handler code
        print "OnTool_tbSave()"
#!XRCED:end-block:xrcappFrame.OnTool_tbSave        

#!XRCED:begin-block:xrcappFrame.OnTool_tbSaveAs
    def OnTool_tbSaveAs(self, evt):
        # Replace with event handler code
        print "OnTool_tbSaveAs()"
#!XRCED:end-block:xrcappFrame.OnTool_tbSaveAs        

#!XRCED:begin-block:xrcappFrame.OnButton_fooButton
    def OnButton_fooButton(self, evt):
        # Replace with event handler code
        print "OnButton_fooButton()"
#!XRCED:end-block:xrcappFrame.OnButton_fooButton        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    gui_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxFrame" name="appFrame">
    <object class="wxMenuBar" name="appMenu">
      <object class="wxMenu" name="fileMenu">
        <label>File</label>
        <object class="wxMenuItem" name="new">
          <label>New</label>
          <bitmap stock_id="wxART_NEW"/>
          <accel>ctrl-n</accel>
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
        <object class="wxMenuItem" name="open">
          <label>&amp;Open</label>
          <bitmap stock_id="wxART_FILE_OPEN"/>
          <accel>ctrl-o</accel>
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
        <object class="wxMenuItem" name="save">
          <label>&amp;Save</label>
          <bitmap stock_id="wxART_FILE_SAVE"/>
          <accel>ctrl-s</accel>
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
        <object class="wxMenuItem" name="saveAs">
          <label>Save &amp;As</label>
          <bitmap stock_id="wxART_FILE_SAVE_AS"/>
          <accel>ctrl-shift-s</accel>
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
        <object class="wxMenuItem" name="exit">
          <label>&amp;Quit</label>
          <bitmap stock_id="wxART_QUIT"/>
          <accel>ctrl-q</accel>
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
      </object>
      <object class="wxMenu" name="editMenu"/>
    </object>
    <object class="wxToolBar" name="basicTools">
      <object class="tool" name="tbNew">
        <bitmap stock_id="wxART_NEW"/>
        <label>New</label>
        <XRCED>
          <events>EVT_TOOL</events>
        </XRCED>
      </object>
      <object class="tool" name="tbSave">
        <bitmap stock_id="wxART_FILE_SAVE"/>
        <label>Save</label>
        <XRCED>
          <events>EVT_TOOL</events>
        </XRCED>
      </object>
      <object class="tool" name="tbSaveAs">
        <bitmap stock_id="wxART_FILE_SAVE_AS"/>
        <label>Save As</label>
        <XRCED>
          <events>EVT_TOOL</events>
        </XRCED>
      </object>
    </object>
    <object class="wxStatusBar" name="appStatus"/>
    <object class="wxPanel" name="basePanel">
      <object class="wxBoxSizer">
        <object class="sizeritem">
          <object class="wxButton" name="fooButton">
            <label>CLICK HERE</label>
            <XRCED>
              <events>EVT_BUTTON</events>
            </XRCED>
          </object>
        </object>
        <object class="sizeritem">
          <object class="wxStaticText" name="changeMe">
            <size>90,20</size>
            <label>LABEL</label>
            <style>wxALIGN_CENTRE</style>
          </object>
        </object>
        <orient>wxVERTICAL</orient>
      </object>
    </object>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/gui/gui_xrc', gui_xrc)
    __res.Load('memory:XRC/gui/gui_xrc')


# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("File")
    _("New")
    _("&Open")
    _("&Save")
    _("Save &As")
    _("&Quit")
    _("New")
    _("Save")
    _("Save As")
    _("CLICK HERE")
    _("LABEL")

